Routes:
  /:
    Methods:
      - GET
      - POST
    Controller: Cuckoo\Http\Controllers\Controller::Index
    Privacy : 
      - public # TODO: here we can block requests if the session is not authenticated.
